# Generated by Django 4.2.3 on 2023-07-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=0, upload_to='productimg'),
            preserve_default=False,
        ),
    ]
