# Generated by Django 4.2.3 on 2023-08-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_post_image_small'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=155)),
                ('username', models.CharField(max_length=155)),
                ('email', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('address_additional', models.TextField()),
                ('phone', models.CharField(max_length=13)),
            ],
        ),
    ]
