# Generated by Django 4.2.3 on 2023-07-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=0, max_length=110),
            preserve_default=False,
        ),
    ]
